### ISSUE TITLE
php error on 2.6 dev

### ISSUE THREAD

**Issue by fsamareanu** [theonemcdonald/pfSense-pkg-WireGuard#31] opened 2021-04-20 15:46 UTC
Hello,

There's a PHP error in vpn-wireguard with 0.6:

Warning: Illegal string offset 'peers' in /usr/local/www/wg/vpn_wg.php on line 101 Warning: Illegal string offset 'peers' in /usr/local/www/wg/vpn_wg.php on line 104 Fatal error: Uncaught Error: Cannot use string offset as an array in /usr/local/www/wg/vpn_wg.php:104 Stack trace: #0 {main} thrown in /usr/local/www/wg/vpn_wg.php on line 104 PHP ERROR: Type: 1, File: /usr/local/www/wg/vpn_wg.php, Line: 104, Message: Uncaught Error: Cannot use string offset as an array in /usr/local/www/wg/vpn_wg.php:104 Stack trace: #0 {main} thrown

I was able to go directly to the edit page and create the tunnel (which works) but I'm not able to edit the tunnel as the page is blank:

![image](https://user-images.githubusercontent.com/38040820/115425725-647b7400-a1ef-11eb-86ee-4f51ab071414.png)

Package versions:

pfSense-pkg-WireGuard-0.0.6    pfSense package WireGuard
wireguard-kmod-0.0.20210415    WireGuard implementation for the FreeBSD kernel
wireguard-tools-1.0.20210315_4 Fast, modern and secure VPN Tunnel

PFSense version: 2.6.0.a.20210416.0100

Edit: issue can be reproduced on a 2.5.1 system as well but with a slightly different message:

Fatal error: Uncaught Error: Cannot use string offset as an array in /usr/local/www/wg/vpn_wg.php:112 Stack trace: #0 {main} thrown in /usr/local/www/wg/vpn_wg.php on line 112 PHP ERROR: Type: 1, File: /usr/local/www/wg/vpn_wg.php, Line: 112, Message: Uncaught Error: Cannot use string offset as an array in /usr/local/www/wg/vpn_wg.php:112 Stack trace: #0 {main} thrown

**Comment by theonemcdonald** [comment] 2021-04-20 17:29
Root cause found, will be releasing v0.0.6_3 that will fix it. Will work on 2.5.1 and 2.6.0+. PHP was upgraded in 2.6.0 that broke something here. I had been developing against 2.6.0 but shifted to 2.5.1 several days ago... my mistake.

**Comment by fsamareanu** [comment] 2021-04-20 18:13
Hello,

The issue persists after upgrading to pfSense-pkg-WireGuard-0.0.6_3.txz on both 2.6 and 2.5. Any extra debug information I can provide?

2.6 error:

Warning: Illegal string offset 'peers' in /usr/local/www/wg/vpn_wg.php on line 111 Warning: Illegal string offset 'peers' in /usr/local/www/wg/vpn_wg.php on line 114 Fatal error: Uncaught Error: Cannot use string offset as an array in /usr/local/www/wg/vpn_wg.php:114 Stack trace: #0 {main} thrown in /usr/local/www/wg/vpn_wg.php on line 114 PHP ERROR: Type: 1, File: /usr/local/www/wg/vpn_wg.php, Line: 114, Message: Uncaught Error: Cannot use string offset as an array in /usr/local/www/wg/vpn_wg.php:114 Stack trace: #0 {main} thrown

2.5 error:

Fatal error: Uncaught Error: Cannot use string offset as an array in /usr/local/www/wg/vpn_wg.php:114 Stack trace: #0 {main} thrown in /usr/local/www/wg/vpn_wg.php on line 114 PHP ERROR: Type: 1, File: /usr/local/www/wg/vpn_wg.php, Line: 114, Message: Uncaught Error: Cannot use string offset as an array in /usr/local/www/wg/vpn_wg.php:114 Stack trace: #0 {main} thrown

**Comment by theonemcdonald** [comment] 2021-04-20 18:23
can you redact and post your <wireguard></wireguard> block from config.xml?

**Comment by fsamareanu** [comment] 2021-04-20 18:28
2.5.1 (basically a vanilla 2.5.1 with no setup done in UI):

                <wireguard>
                        <config>
                                <address>REDACTED</address>
                                <listenport>51820</listenport>
                                <dns>REDACTED</dns>
                                <privatekey>REDACTED</privatekey>
                                <publickey></publickey>
                                <mtu>1380</mtu>
                                <table></table>
                                <preup></preup>
                                <postup></postup>
                                <predown></predown>
                                <postdown></postdown>
                        </config>
                        <tunnel></tunnel>
                </wireguard>
                <wireguardpeers></wireguardpeers>

2.6:

                <wireguard>
                        <config>
                                <keep_conf>yes</keep_conf>
                                <hide_secrets></hide_secrets>
                        </config>
                        <tunnel></tunnel>
                        <tunnel>
                                <name>tun_wg0</name>
                                <mtu>1420</mtu>
                                <enabled>yes</enabled>
                                <descr><![CDATA[REDACTED]]></descr>
                                <interface>
                                        <address></address>
                                        <listenport>51820</listenport>
                                        <privatekey>REDACTED</privatekey>
                                        <publickey>REDACTED</publickey>
                                        <mtu>1420</mtu>
                                </interface>
                                <peers>
                                        <wgpeer>
                                                <publickey>REDACTED</publickey>
                                                <endpoint>REDACTED</endpoint>
                                                <allowedips>0.0.0.0/0</allowedips>
                                                <descr><![CDATA[REDACTED]]></descr>
                                                <persistentkeepalive>25</persistentkeepalive>
                                                <presharedkey></presharedkey>
                                                <port>REDACTED/port>
                                                <peerwgaddr></peerwgaddr>
                                        </wgpeer>
                                </peers>
                        </tunnel>
                </wireguard>

**Comment by theonemcdonald** [comment] 2021-04-20 18:31
Something is screwy here, but I need to handle it. 

This structure: 

```
            <wireguard>
                    <config>
                            <address>REDACTED</address>
                            <listenport>51820</listenport>
                            <dns>REDACTED</dns>
                            <privatekey>REDACTED</privatekey>
                            <publickey></publickey>
                            <mtu>1380</mtu>
                            <table></table>
                            <preup></preup>
                            <postup></postup>
                            <predown></predown>
                            <postdown></postdown>
                    </config>
                    <tunnel></tunnel>
            </wireguard>
            <wireguardpeers></wireguardpeers>
```

Is not from my package. But I bet it's being parsed and causing issues. You should delete the above block.

**Comment by fsamareanu** [comment] 2021-04-20 18:35
This box never had a custom package installed (except the short lived netgate provided one). I removed the lines from the 2.5 installation and now the page works. Any idea what the 2.6 issue is?

**Comment by theonemcdonald** [comment] 2021-04-20 18:37
The box might now have, but your configuration definitely did at some point.

As for the 2.6 installation, the issue is poor handling of that empty `<tunnel></tunnel>` block. I am able to replicate this now.

**Comment by fsamareanu** [comment] 2021-04-20 18:41
I removed the empty tunnel definition and now it displays properly in 2.6. Thank you for your help. You can close this whenever you push whatever fixes you have in mind.

**Comment by theonemcdonald** [comment] 2021-04-20 19:14
Thanks, I would like to handle this situation gracefully. I'm going to close this, but will be working on it. It shouldn't impact anyone with a truly clean install.

**Closed by theonemcdonald** 2021-04-20 19:14 UTC

**Comment by theonemcdonald** [comment] 2021-04-20 19:43
Just for reference, I can replicate this "bug" (creating an empty `<tunnel></tunnel>` block) even on 2.5.0. Low priority.
