### ISSUE TITLE
if_wg fails to load on SG-3100

### ISSUE THREAD

**Issue by gshaffer1** [theonemcdonald/pfSense-pkg-WireGuard#71] opened 2021-05-11 15:56 UTC
Installed v0.0.9 packages on SG-3100 running pfSense+ 21.02.2, no reported errors on pkg install.

Packages loaded:
- pfSense-pkg-WireGuard-0.0.9.txz
- wireguard-kmod-0.0.20210503.txz
- wireguard-tools-lite-1.0.20210424.txz

WireGuard Status GUI banner shows the kmod is not loaded, verified with kldstat.

Manually load of if_wg ("kldload if_wg") returns:
kldload: an error occurred while loading module if_wg. Please check dmesg(8) for more details.

dmesg returns:
kldload: /boot/modules/if_wg.ko: Unsupported file layout

**Comment by theonemcdonald** [comment] 2021-05-11 16:17
Likely caused by the fact that the kmod I'm providing isn't compiled for ARM. I'm getting some Netgate hardware soon to test on.

**Comment by gshaffer1** [comment] 2021-05-11 16:59
Thats what I suspected as the same packages loaded fine on my Protectli box with an intel processors. Let me know if there is anything I can do to help you out with this.

**Comment by gshaffer1** [comment] 2021-05-12 01:45
I've got an SG-1100 you can have it will help you with this project.

**Comment by Tigger2014** [comment] 2021-05-12 20:10
@gshaffer1  please can you provide the output of `uname -a` for the SG-3100

**Comment by theonemcdonald** [comment] 2021-05-12 20:12
> I've got an SG-1100 you can have it will help you with this project.

Shoot me an email : rcmcdonald91@gmail.com ! :)

**Comment by gshaffer1** [comment] 2021-05-12 21:23
> @gshaffer1 please can you provide the output of `uname -a` for the SG-3100

FreeBSD X.Y.org 12.2-STABLE FreeBSD 12.2-STABLE c1120650645f(plus-RELENG_21_02) pfSense-SG-3100  arm

**Comment by theonemcdonald** [comment] 2021-05-14 17:20
I'm going to go ahead and close this. Hang tight, there is ongoing work to make the package more accessible to users on both x64 and ARM, and on both stable and devel branches :)

**Comment by vajonam** [comment] 2021-05-18 18:50
@gshaffer1 if you want try out these builds on your ARM box. I dont have one to test https://packages.mced.tech/packages/armv7x-main/

**Comment by gshaffer1** [comment] 2021-05-18 23:16
> @gshaffer1 if you want try out these builds on your ARM box. I dont have one to test https://packages.mced.tech/packages/armv7x-main/

These work! I loaded them, created a tunnel and peer and was able to connect to the box from the outside. Didn't do an exhaustive test, but was able to ping some systems on the other side.

**Comment by vajonam** [comment] 2021-05-19 01:17
@gshaffer1  that URL will be going away .. Try the install instructions here this will add a repo to your pfsense (dont do it on prod) just in case.. something you can roll back on. 

https://github.com/theonemcdonald/pfSense-pkg-WireGuard/wiki/Installation

**Comment by gshaffer1** [comment] 2021-05-19 16:30
> @gshaffer1 that URL will be going away .. Try the install instructions here this will add a repo to your pfsense (dont do it on prod) just in case.. something you can roll back on.
> 
> https://github.com/theonemcdonald/pfSense-pkg-WireGuard/wiki/Installation

That worked out great!!!

**Comment by Tigger2014** [comment] 2021-05-20 20:40
@gshaffer1  could you provide the output of `uname -m` if you don't mind?

**Comment by vajonam** [comment] 2021-05-21 15:07
@gshaffer1 just FYI we re-orged stuff so you will need to remove repo and re-add. it should auto pickup you arch and load the right rep please let us know if this works.

**Comment by gshaffer1** [comment] 2021-05-21 21:04
> @gshaffer1 could you provide the output of `uname -m` if you don't mind?

FreeBSD X.Y.org 12.2-STABLE FreeBSD 12.2-STABLE c1120650645f(plus-RELENG_21_02) pfSense-SG-3100 arm

**Comment by gshaffer1** [comment] 2021-05-21 21:23
> @gshaffer1 just FYI we re-orged stuff so you will need to remove repo and re-add. it should auto pickup you arch and load the right rep please let us know if this works.

This worked on my box running 2.5.1 but not on my other box (SG-3100) running 21.02.2.

Output from running command:

Hmm...  Looks like a unified diff to me...
The text leading up to this was:
--------------------------
|--- /etc/inc/pkg-utils.orig.inc 2021-02-18 11:18:07.356449000 -0300
|+++ /etc/inc/pkg-utils.inc      2021-02-18 15:26:41.486078000 -0300
--------------------------
Patching file /etc/inc/pkg-utils.inc using Plan A...
Hunk #1 succeeded at 410 (offset 8 lines).
Hunk #2 succeeded at 507 (offset 8 lines).
done
Updating Unofficial repository catalogue...
pkg: https://packages.mced.tech/packages/freebsd_12-2_arm-ng_ports_251/meta.txz: Not Found
repository Unofficial has no meta file, using default settings
pkg: https://packages.mced.tech/packages/freebsd_12-2_arm-ng_ports_251/packagesite.txz: Not Found
Unable to update repository Unofficial
Updating pfSense-core repository catalogue...
pfSense-core repository is up to date.
Updating pfSense repository catalogue...
pfSense repository is up to date.
Error updating repositories!

**Comment by Tigger2014** [comment] 2021-05-21 21:36
@gshaffer1 the script has been updated. Can you try again on the 3100?

**Comment by vajonam** [comment] 2021-05-21 21:40
all always `remove` and `install_repo.sh` again please.

**Comment by vajonam** [comment] 2021-05-21 21:41
just reopening this as this is ongoing and will be closed again when totally fixed.

**Comment by gshaffer1** [comment] 2021-05-21 21:45
> @gshaffer1 the script has been updated. Can you try again on the 3100?

Ran the remove script and then ran the install script, work fine.

Output from command:

Hmm...  Looks like a unified diff to me...
The text leading up to this was:
--------------------------
|--- /etc/inc/pkg-utils.orig.inc 2021-02-18 11:18:07.356449000 -0300
|+++ /etc/inc/pkg-utils.inc      2021-02-18 15:26:41.486078000 -0300
--------------------------
Patching file /etc/inc/pkg-utils.inc using Plan A...
Hunk #1 succeeded at 410 (offset 8 lines).
Hunk #2 succeeded at 507 (offset 8 lines).
done
Updating Unofficial repository catalogue...
Fetching meta.conf: . done
Fetching packagesite.txz: . done
Processing entries: . done
Unofficial repository update completed. 7 packages processed.
Updating pfSense-core repository catalogue...
pfSense-core repository is up to date.
Updating pfSense repository catalogue...
pfSense repository is up to date.
All repositories are up to date.

**Comment by theonemcdonald** [comment] 2021-06-01 11:50
I'm going to close this. We are now being built in the Netgate 2.5.2 beta (and I believe 21.05) repos.

**Closed by theonemcdonald** 2021-06-01 11:50 UTC
Labels: bug, in progress
