### ISSUE TITLE
pfSense pops warning message upon reboot.

### ISSUE THREAD

**Issue by mfld-pub** [theonemcdonald/pfSense-pkg-WireGuard#19] opened 2021-04-16 09:00 UTC
This is an exciting project I look forward to testing!

pfSense 2.5.1-RELEASE (amd64)

Installed precompiled binaries from https://github.com/theonemcdonald/pfSense-pkg-WireGuard/releases/tag/v0.0.4_2

Configured Interface and a peer, set NAT Outbound and Firewall rules. Peer was able to connect.

Rebooted. Now peer cannot connect. pfSense GUI pops these errors:

![wg8](https://user-images.githubusercontent.com/66289900/114999470-13f0d780-9ecc-11eb-9d34-83a37e73dff7.JPG)

Tried 

```
/usr/local/etc/rc.reload_wireguard
wg-quick: `wg0' already exists

```
The interface seems up.

**Comment by mfld-pub** [comment] 2021-04-16 09:04
I suspect is is related to my workflow, initial test I had not gone to interface assignments. I did that after and then rebooted. I see in the docu here: 

> Assigned interfaces are now configured under the traditional pfSense interfaces.php page. Unassigned tunnels are still configured through the WireGuard UI.
> Gateways are no longer automatically created for tunnels assigned to pfSense interfaces. Just like any other WAN, you will now be required to create your own gateway entries for the tunnel remote side if you intended to route traffic over the tunnel itself.

Indeed, wg0 has no IP addresses assigned to it anymore :) I shall amend the setup workflow to assign an IF first, create GWs and then put the IP addresses there.

**Comment by theonemcdonald** [comment] 2021-04-16 10:25
Hi @mfld-pub , yea you've found one major pressing issue still. It is caused by the order of execution at startup.

1. rc.bootstrap_wireguard runs first to build temporary lo loopbacks of any assigned tunnel interface (phase 1)...this protects the firewall from being unable to boot if phase 2 fails for whatever reason (say the WireGuard package was uninstalled, etc.).
2. rc.reload_wireguard (phase 2) runs to build WireGuard tunnels using wg-quick.
3. pfSense takes over and configures it's assigned interfaces
4. Much later when packages are loaded, pfSense initiates a package resync event for each package. Currently in my code, a resync tears down any wireguard tunnel and rebuilds it. This is fine for tunnels that are not assigned to interfaces. However, for assigned interfaces, this means that the IP address will be lost.

I'm working on it! I'm hoping to have a fix for this by weekend

Thanks for testing! :)

**Comment by theonemcdonald** [comment] 2021-04-16 15:59
I'm going to close this issue because there isn't anything I am going to do about it...Netgate will have to remove the checks

As for assigned interfaces, that should be fixed now.

**Closed by theonemcdonald** 2021-04-16 15:59 UTC
Labels: bug
